server:
  port: 2000

spring:
  cloud:
    gateway:
      routes:
        - id: user-cmd-register
          uri: http://localhost:8081/api/v1/user/register/**
          order: 1
          predicates:
          - Path=/api/v1/user/register/**

        - id: user-cmd-update
          uri: http://localhost:8081/api/v1/user/update/**
          order: 2
          predicates:
            - Path=/api/v1/user/update/**

        - id: user-cmd-delete
          uri: http://localhost:8081/api/v1/user/delete/**
          order: 3
          predicates:
            - Path=/api/v1/user/delete/**

        - id: user-query
          uri: http://localhost:8082/api/v1/user/**
          order: 4
          predicates:
            - Path=/api/v1/user/**


        - id: bank-cmd-open
          uri: http://localhost:9091/api/v1/bank/open/**
          order: 1
          predicates:
            - Path=/api/v1/bank/open/**

        - id: bank-cmd-deposit
          uri: http://localhost:9091/api/v1/bank/deposit/**
          order: 2
          predicates:
            - Path=/api/v1/bank/deposit/**

        - id: bank-cmd-withdraw
          uri: http://localhost:9091/api/v1/bank/withdraw/**
          order: 3
          predicates:
            - Path=/api/v1/bank/withdraw/**

        - id: bank-cmd-close
          uri: http://localhost:9091/api/v1/bank/close/**
          order: 4
          predicates:
            - Path=/api/v1/bank/close/**

        - id: bank-query
          uri: http://localhost:9092/api/v1/bank/**
          order: 5
          predicates:
            - Path=/api/v1/bank/**

