server:
  port: 9092

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bank
      auto-index-creation: true
  datasource:
    url: jdbc:mysql://localhost:3306/bank
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8083

